[project]
name = "crypto-analyser-contract"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.crypto-analyser]
path = "contracts/crypto-analyser.clar"
depends_on = []

[contracts.crypto-analytics-enhanced]
path = "contracts/crypto-analytics-enhanced.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
